WAIT UNTIL ETA:APOAPSIS < 20.
LOCK STEERING TO RETROGRADE.
WAIT 3.
LOCK THROTTLE TO 1.
WAIT UNTIL OBT:HASNEXTPATCH = False.
LOCK THROTTLE TO 0.
PRINT "CIRCULARIZING".
SET T_AP TO PERIAPSIS * 0.95.
WAIT 1.
LOCK STEERING TO RETROGRADE.
LOCK THROTTLE TO 1.
WAIT UNTIL PERIAPSIS < T_AP.
LOCK THROTTLE TO 0.