WAIT 5.
LOCK STEERING TO HEADING (90,90).
LOCK THROTTLE TO 1.
STAGE.
WAIT 1.
SET PTHRUST TO MAXTHRUST.
UNTIL (APOAPSIS > 80000){

	IF PTHRUST - MAXTHRUST > 10 {
		LOCK THROTTLE TO 0. WAIT 1. STAGE. WAIT 1. LOCK THROTTLE TO 1. WAIT 1.
	}
	SET PTHRUST TO MAXTHRUST.
	WAIT 0.5.

}
LOCK THROTTLE TO 0. WAIT 1.
STAGE. STAGE. STAGE.
UNTIL ALTITUDE < 20000 {LOCK STEERING TO SRFRETROGRADE. WAIT 1.}
LOCK THROTTLE TO 1.
WAIT UNTIL VERTICALSPEED > -100.
LOCK THROTTLE TO 0.